INCLUDES = -std=c++17
CC = g++
LIBS = 
CFLAGS = -Werror
OBJS1 =  q1.cpp
OBJS2 =  q2.cpp

PA2_Q1: ${OBJS1}
   ${CC} ${INCLUDES} ${CFLAGS} ${OBJS1}
PA2_Q2345: ${OBJS2}
   ${CC} ${INCLUDES} ${CFLAGS} ${OBJS2}